#============= CONSTANTS ==================
KEYPOINT_MODE_GRID = "grid"
KEYPOINT_MODE_SIFT = "sift"
KEYPOINT_MODE_SIFT_CLUSTER = "sift_cluster"
KEYPOINT_MODE_SINGLESHOT = "single"

PATCH_SAVEMODE_WRITER = "writer"
PATCH_SAVEMODE_PAGE = "page"
PATCH_SAVEMODE_CLUSTER = "pseudo"
PATCH_SAVEMODE_NONE = "none"

TRAIN_MODE_MAE = 1
TRAIN_MODE_DINO = 2
TRAIN_MODE_IBOT = 3
TRAIN_MODE_ATTMASK = 4